import type { Challenge } from "./types";

export const CHALLENGES: Challenge[] = [
  {
    id: "first-commit",
    chapter: "仓门初启",
    title: "第一枚 Commit",
    summary: "从空目录开始建立版本意识，把第一份说明文档纳入历史。",
    objectives: ["让当前目录成为 Git 仓库", "准备一份 README 文档", "把文档纳入下一次提交", "留下第一条历史记录"],
    hints: ["先让目录具备版本库身份。", "文件创建后还不等于进入历史，需要经过暂存。", "提交信息可以很短，但必须表达这次变化。"],
    kind: "commit",
    difficulty: "入门",
    baseXp: 40,
    commands: ["git init", "touch README.md", "git add README.md", "git commit -m init"],
  },
  {
    id: "staging-focus",
    chapter: "暂存炼气",
    title: "暂存区入门",
    summary: "在工作区和暂存区之间做选择，只把本轮需要的内容送入提交。",
    objectives: ["创建本轮任务文件", "观察工作区状态", "只暂存指定文件", "完成一次提交"],
    hints: ["先看清当前文件处于哪个区域。", "暂存区像提交前的候选名单。", "确认候选名单无误后再提交。"],
    kind: "staging",
    difficulty: "入门",
    baseXp: 35,
    commands: ["touch app.js", "git status", "git add app.js", "git commit -m add-app"],
  },
  {
    id: "branch-sword",
    chapter: "分支御剑",
    title: "创建并切换分支",
    summary: "从主线分出实验路径，在独立分支里推进新能力。",
    objectives: ["创建一条功能分支", "进入这条新分支", "在分支中准备功能文档", "把变化放入候选区"],
    hints: ["分支先被创建，随后才需要切换过去。", "确认自己已经离开主线再做实验。", "本关暂不要求提交，重点是分支位置。"],
    kind: "branch",
    difficulty: "进阶",
    baseXp: 50,
    commands: ["git branch feature", "git checkout feature", "touch feature.md", "git add feature.md"],
  },
  {
    id: "merge-river",
    chapter: "合并渡河",
    title: "让分支汇流",
    summary: "回到主线接纳功能分支，让两条提交路径重新汇合。",
    objectives: ["回到主线", "把功能分支并入主线", "检查合并后的状态"],
    hints: ["合并前要站在接收变化的分支上。", "合并不是复制文件，而是整合提交线。", "完成后观察是否还有未处理变化。"],
    kind: "merge",
    difficulty: "进阶",
    baseXp: 55,
    commands: ["git checkout main", "git merge feature", "git status"],
  },
  {
    id: "reset-path",
    chapter: "回溯问心",
    title: "撤回错误脚步",
    summary: "理解历史指针的位置，撤回最近一次提交但保留修改痕迹。",
    objectives: ["查看最近历史", "让历史指针回到上一步", "确认修改仍留在可处理区域"],
    hints: ["先观察历史，才能知道要回到哪里。", "本关需要保留改动，不是彻底丢弃。", "回溯后再看一次状态。"],
    kind: "history",
    difficulty: "突破",
    baseXp: 60,
    commands: ["git log", "git reset --soft HEAD~1", "git status"],
  },
  {
    id: "conflict-calm",
    chapter: "冲突破境",
    title: "解决一次冲突",
    summary: "面对同一文件的分歧，标记已经处理并完成合并记录。",
    objectives: ["查看冲突状态", "标记冲突文件已解决", "提交解决结果"],
    hints: ["先确认哪些文件仍处在冲突状态。", "解决后的文件需要重新进入候选区。", "最后留下合并处理记录。"],
    kind: "conflict",
    difficulty: "突破",
    baseXp: 70,
    commands: ["git status", "git add story.md", "git commit -m resolve-conflict"],
  },
];

export const getChallenge = (challengeId: string) =>
  CHALLENGES.find((challenge) => challenge.id === challengeId);
