import type { Challenge } from "./types";

export const CHALLENGES: Challenge[] = [
  {
    id: "first-commit",
    chapter: "仓门初启",
    title: "第一枚 Commit",
    summary: "从空目录开始建立版本意识，把第一份说明文档纳入历史。",
    skill: "仓库初始化 / 暂存 / 提交",
    concept: "commit 是一次版本快照；文件必须先进入暂存区，才能被写入下一次提交。",
    repositoryStates: ["普通文件夹", "已初始化仓库", "README 位于工作区", "README 位于暂存区", "历史中出现第一条提交"],
    objectives: ["让当前目录成为 Git 仓库", "准备一份 README 文档", "把文档纳入下一次提交", "留下第一条历史记录"],
    hints: ["先让目录具备版本库身份。", "文件创建后还不等于进入历史，需要经过暂存。", "提交信息可以很短，但必须表达这次变化。"],
    hintLevels: ["仓库要先拥有 .git 目录。", "新文件进入历史前，需要先被 add 到暂存区。", "可以依次尝试：git init、touch README.md、git add README.md、git commit -m init。"],
    kind: "commit",
    difficulty: "入门",
    baseXp: 40,
    commands: ["git init", "touch README.md", "git add README.md", "git commit -m init"],
  },
  {
    id: "staging-focus",
    chapter: "暂存炼气",
    title: "暂存区入门",
    summary: "在工作区和暂存区之间做选择，只把本轮需要的内容送入提交。",
    skill: "状态查看 / 精确暂存 / 提交",
    concept: "暂存区决定下一次提交包含哪些内容，Git 不会自动把工作区所有变化写入历史。",
    repositoryStates: ["工作区准备产生变化", "app.js 位于工作区", "status 展示未暂存变化", "app.js 位于暂存区", "历史中出现 app.js 提交"],
    objectives: ["创建本轮任务文件", "观察工作区状态", "只暂存指定文件", "完成一次提交"],
    hints: ["先看清当前文件处于哪个区域。", "暂存区像提交前的候选名单。", "确认候选名单无误后再提交。"],
    hintLevels: ["先制造一个可观察的工作区变化。", "status 可以告诉你文件是否已经 staged。", "本关路径是 touch app.js、git status、git add app.js、git commit -m add-app。"],
    kind: "staging",
    difficulty: "入门",
    baseXp: 35,
    commands: ["touch app.js", "git status", "git add app.js", "git commit -m add-app"],
  },
  {
    id: "branch-sword",
    chapter: "分支御剑",
    title: "创建并切换分支",
    summary: "从主线分出实验路径，在独立分支里推进新能力。",
    skill: "分支创建 / 分支切换 / 分支内暂存",
    concept: "分支是一条独立开发线；切到功能分支后再改动，可以避免直接影响主线。",
    repositoryStates: ["位于 main 主线", "feature 分支已创建", "HEAD 指向 feature", "feature.md 位于工作区", "feature.md 位于暂存区"],
    objectives: ["创建一条功能分支", "进入这条新分支", "在分支中准备功能文档", "把变化放入候选区"],
    hints: ["分支先被创建，随后才需要切换过去。", "确认自己已经离开主线再做实验。", "本关暂不要求提交，重点是分支位置。"],
    hintLevels: ["先创建 feature 分支。", "创建后还需要 checkout 到新分支。", "本关路径是 git branch feature、git checkout feature、touch feature.md、git add feature.md。"],
    kind: "branch",
    difficulty: "进阶",
    baseXp: 50,
    commands: ["git branch feature", "git checkout feature", "touch feature.md", "git add feature.md"],
  },
  {
    id: "merge-river",
    chapter: "合并渡河",
    title: "让分支汇流",
    summary: "回到主线接纳功能分支，让两条提交路径重新汇合。",
    skill: "切回主线 / 合并分支 / 状态确认",
    concept: "合并要站在接收变化的分支上执行，merge 会把另一条开发线的提交整合进当前分支。",
    repositoryStates: ["位于 feature 分支之后", "HEAD 回到 main", "feature 合入 main", "工作区保持干净"],
    objectives: ["回到主线", "把功能分支并入主线", "检查合并后的状态"],
    hints: ["合并前要站在接收变化的分支上。", "合并不是复制文件，而是整合提交线。", "完成后观察是否还有未处理变化。"],
    hintLevels: ["main 是本关接收变化的分支。", "回到 main 后再执行 merge。", "本关路径是 git checkout main、git merge feature、git status。"],
    kind: "merge",
    difficulty: "进阶",
    baseXp: 55,
    commands: ["git checkout main", "git merge feature", "git status"],
  },
  {
    id: "reset-path",
    chapter: "回溯问心",
    title: "撤回错误脚步",
    summary: "理解历史指针的位置，撤回最近一次提交但保留修改痕迹。",
    skill: "历史查看 / soft reset / 状态确认",
    concept: "reset 会移动历史指针；soft 模式撤回提交记录，但保留已经暂存的修改。",
    repositoryStates: ["历史中已有可撤回提交", "log 展示最近提交", "HEAD 回到上一个提交", "修改仍保留在可提交区域"],
    objectives: ["查看最近历史", "让历史指针回到上一步", "确认修改仍留在可处理区域"],
    hints: ["先观察历史，才能知道要回到哪里。", "本关需要保留改动，不是彻底丢弃。", "回溯后再看一次状态。"],
    hintLevels: ["先用 log 观察 HEAD 附近的历史。", "soft reset 会撤回提交但保留变化。", "本关路径是 git log、git reset --soft HEAD~1、git status。"],
    kind: "history",
    difficulty: "突破",
    baseXp: 60,
    commands: ["git log", "git reset --soft HEAD~1", "git status"],
  },
  {
    id: "conflict-calm",
    chapter: "冲突破境",
    title: "解决一次冲突",
    summary: "面对同一文件的分歧，标记已经处理并完成合并记录。",
    skill: "冲突状态查看 / 标记解决 / 合并提交",
    concept: "冲突不是失败，而是 Git 无法替你判断取舍；人工处理后需要重新 add，再提交解决结果。",
    repositoryStates: ["合并产生冲突", "status 展示冲突文件", "story.md 被标记为已解决", "历史中留下冲突解决提交"],
    objectives: ["查看冲突状态", "标记冲突文件已解决", "提交解决结果"],
    hints: ["先确认哪些文件仍处在冲突状态。", "解决后的文件需要重新进入候选区。", "最后留下合并处理记录。"],
    hintLevels: ["先用 status 定位冲突文件。", "手动处理后，Git 需要你 add 来确认解决。", "本关路径是 git status、git add story.md、git commit -m resolve-conflict。"],
    kind: "conflict",
    difficulty: "突破",
    baseXp: 70,
    commands: ["git status", "git add story.md", "git commit -m resolve-conflict"],
  },
];

export const getChallenge = (challengeId: string) =>
  CHALLENGES.find((challenge) => challenge.id === challengeId);
