server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/ {
    proxy_pass http://backend:3000/auth/;
  }
  location /levels/ {
    proxy_pass http://backend:3000/levels/;
  }
  location /levels {
    proxy_pass http://backend:3000/levels;
  }
  location /attempts/ {
    proxy_pass http://backend:3000/attempts/;
  }
  location /leaderboard {
    proxy_pass http://backend:3000/leaderboard;
  }
  location /home/ {
    proxy_pass http://backend:3000/home/;
  }
  location /users/ {
    proxy_pass http://backend:3000/users/;
  }
  location /admin/ {
    proxy_pass http://backend:3000/admin/;
  }
}
